# Generated by Django 5.2.6 on 2025-12-06 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcementboard',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='classmember',
            options={},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='discussionreply',
            options={'ordering': ['-is_answer', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='learningresource',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='progresstracking',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='discussion',
            name='classroom_d_classro_c62ba4_idx',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=20),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='topic',
            field=models.CharField(choices=[('general', 'General'), ('doubt', 'Doubt'), ('project', 'Project'), ('resource', 'Resource'), ('peer_learning', 'Peer Learning')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='resource_type',
            field=models.CharField(choices=[('document', 'Document'), ('video', 'Video'), ('link', 'External Link'), ('presentation', 'Presentation'), ('file', 'File')], max_length=30),
        ),
    ]
