# Generated by Django 5.2.6 on 2025-12-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamificationstats',
            options={},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='gamificationstats',
            name='badges',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='gamificationstats',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('quiz_attempt', 'Quiz Attempt'), ('quiz_submission', 'Quiz Submission'), ('discussion_post', 'Discussion Post'), ('attendance', 'Attendance'), ('resource_view', 'Resource View')], max_length=50),
        ),
    ]
